### ISSUE TITLE
Merge registration and intervention endpoints into one

### ISSUE THREAD

**Issue by ghelobytes** [globalmangrovewatch/gmw-api#107]
**Task part 1**
- [x] Create controller `RegistrationInterventionController`
- [x] Create model/table `registration_intervention_answers`
- [x] Copy existing data from `registration_answers` to `registration_intervention_answers` DB table

**Task part 2**
- [x] Delete endpoint `api/v2/registration_answers`
- [x] Delete endpoint `api/v2/intervention_answers`
- [x] Delete controller/view/model/table `registration_answers`
- [x] Delete controller/view/model/table `intervention_answers`
