### ISSUE TITLE
Add spatial query to dashboard endpoint

### ISSUE THREAD

**Issue by ghelobytes** [globalmangrovewatch/gmw-api#81]
Related ticket: https://github.com/globalmangrovewatch/gmw-users/issues/241

### Tasks
- [x] Enable POSTGIS extension
  -  https://github.com/rgeo/activerecord-postgis-adapter#upgrading-an-existing-database
- [x] Add geometry column to sites and call it `area`
- [x] Value of `sites.area` is extracted from question `1.3`
- [x] Update value of `sites.area` every time `registration_answers` is updated and update includes changes in Question `1.3` (overall site area)
- [x] Endpoint will look like `/api/dashboard/sites?extent=xmin,ymin,xmax,ymax` 
- [x] Perform intersection query between `extent` and `sites.area` and return the resulting sites
- [x] Add geo build pack to Heroku: https://github.com/heroku/heroku-geo-buildpack.git

**Comment by ghelobytes** [comment]
`Places` are locations shown in this list https://mangrove-atlas-api.herokuapp.com/api/v2/locations

Summary of `location_type`:
```
{
  "worldwide": 1,
  "wdpa": 158,
  "country": 102,
  "aoi": 2
}
```

**Comment by ghelobytes** [comment]
- Assume endpoint is `api/dashboard/sites`
- Instead of integrating with `locations` table, just pass the extent of each places to the endpoint: `api/dashboard/sites?extent=xmin,ymin,xmax,ymax`
- Convert polygon (place) to extent:
```
# sample locations data
{
  "id": 993,
  "iso": "AUS",
  "bounds": {
    "coordinates": [
      [
        [109.23347930458496, -58.44943438453255],
        [164.69123430943776, -58.44943438453255],
        [164.69123430943776, -8.881882731189767],
        [109.23347930458496, -8.881882731189767],
        [109.23347930458496, -58.44943438453255]
      ]
    ],
    "geodesic": false,
    "type": "Polygon"
  }
}

# python
from shapely.geometry import Polygon
polygon = Polygon([(0, 0), (1, 1), (1, 0)])
polygon.bounds
(0.0, 0.0, 1.0, 1.0)
```

### OR 
- Accept a `location_id` parameter, query database and grab the `bounds` field: `api/dashboard/sites?location_id=999`

**Comment by ghelobytes** [comment]
PR: https://github.com/globalmangrovewatch/gmw-api/pull/101
Usage: 
```
api/v2/dashboard/sites?extent=minx,miny,maxx,maxy
api/v2/dashboard/sites?extent=-16.1868953704834,12.640254556428197,-16.183032989501953,12.64259955777063
```

**Comment by ghelobytes** [comment]
Generate extent for testing:
```
>>> from shapely.geometry import shape
>>> poly = {
...         "type": "Polygon",
...         "coordinates": [
...           [
...             [
...               -16.1868953704834,
...               12.640254556428197
...             ],
...             [
...               -16.183032989501953,
...               12.640254556428197
...             ],
...             [
...               -16.183032989501953,
...               12.64259955777063
...             ],
...             [
...               -16.1868953704834,
...               12.64259955777063
...             ],
...             [
...               -16.1868953704834,
...               12.640254556428197
...             ]
...           ]
...         ]
...       }
>>>
>>>
>>> poly
{'type': 'Polygon', 'coordinates': [[[-16.1868953704834, 12.640254556428197], [-16.183032989501953, 12.640254556428197], [-16.183032989501953, 12.64259955777063], [-16.1868953704834, 12.64259955777063], [-16.1868953704834, 12.640254556428197]]]}
>>> poly = shape(poly)
>>> poly
<shapely.geometry.polygon.Polygon object at 0x7fc82737e828>
>>> poly.bounds
(-16.1868953704834, 12.640254556428197, -16.183032989501953, 12.64259955777063)
```

**Comment by ghelobytes** [comment]
Implemented. Closing.
